var glo = new Array();function buildGlo() { 
glo[33139] = new Glossary('','battle');
glo[33140] = new Glossary('','Celtic, a people who before the Romans had conquered most of Europe and parts of Asia minor. The Celtic root of their name for themselves was <i>gal-</i> from which the Latin name Gallia is derived. Gallia was the name applied to the Celtic areas of Northern Italy and France. Caesar\'s famous work, the <i>Gallic Wars</i>, a staple of Latin classes, describes the Roman conquest of Gaul, the Celtic areas of France, Belgium, and Switzerland.<p>Celtic languages have been steadily disappearing, receding before other languages since the Roman conquests. Those still spoken today include Welsh, Scots Gaelic, Irish (Erse), and, in France, Breton. Breton is spoken in Brittany (la Bretagne).');
glo[33141] = new Glossary('','present-day');
glo[33142] = new Glossary('','<i>brûler</i> to burn');
glo[33143] = new Glossary('','built (literally: had [someone] built]');
glo[33145] = new Glossary('','<i>relier</i> to connect, join');
glo[33146] = new Glossary('','valley');
glo[33147] = new Glossary('','rail (adjective); relatif aux chemins de fer');
glo[33148] = new Glossary('','un fameux empereur romain'); } buildGlo (); 
